version: "3.8"

services:
  mongo:
    image: mongo:5.0.14
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-root}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-auth-spa}
    ports:
      - ${MONGO_HOST_PORT:-27017}:${MONGO_CONTAINER_PORT:-27017}
    volumes:
      - db:/data/db

  api:
    depends_on:
      - mongo
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    environment:
      - API_PORT=${API_CONTAINER_PORT}
      - MONGO_HOST=mongo
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_PORT=${MONGO_CONTAINER_PORT}
    ports:
      - ${API_HOST_PORT}:${API_CONTAINER_PORT}
    stdin_open: true
    tty: true

volumes:
  db:
